In [12]:
from opt.value_estimator import *
from environment.MarketEnv import *
from common.RangeMap import *
import numpy as np
from opt.bbo_sim_anneal import *


STATE_DIM = 2
ACTION_DIM = 10
BATCH_SIZE = 200

marketEnv = MarketEnv(action_size = ACTION_DIM, max_price = 100, max_inventory = 1, n_agents = 3)

range_dict = {
    (0, 10): 0.10,
    (10, 20): 0.10,
    (20, 30): 0.10,
    (30, 40): 0.10,
    (40, 50): 0.10,
    (50, 60): 0.10,
    (60, 70): 0.10,
    (70, 80): 0.10,
    (80, 90): 0.10,
    (90, 100): 0.10,
}

policy_dic = RangeMapDict(range_dict)

# s -> n -> a
na_policy_dict = dict()
for n in range(marketEnv.n_agents):
    na_policy_dict[n] = policy_dic

# everyone same policy
sna_policy_dict = dict()
for s in range(marketEnv.state_space_size):
    key = repr(list(marketEnv.state_space[s]))
    sna_policy_dict[key] = na_policy_dict

In [13]:
marketEnv.action_space

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [14]:
marketEnv.state_space

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 10.],
       [ 0.,  0.,  0., 20.],
       [ 0.,  0.,  0., 30.],
       [ 0.,  0.,  0., 40.],
       [ 0.,  0.,  0., 50.],
       [ 0.,  0.,  0., 60.],
       [ 0.,  0.,  0., 70.],
       [ 0.,  0.,  0., 80.],
       [ 0.,  0.,  0., 90.]])

In [15]:
value_vector, joint_action_vector = value_search_sample_policy_approx(marketEnv, sna_policy_dict, max_iter = 199)

In [16]:
test_state_index = 1
print(joint_action_vector[test_state_index])
print(marketEnv.state_space[test_state_index])
print(value_vector[test_state_index])

[40. 40. 60.]
[ 0.  0.  0. 10.]
0.09834115348572371


In [17]:
check_state = marketEnv.state_space[test_state_index]
sna_policy_dict[repr(list(check_state))][0][21]

0.1

In [18]:
value_vector

array([0.10128564, 0.09834115, 0.10156604, 0.1020385 , 0.10009589,
       0.10355648, 0.09783579, 0.09990612, 0.1023481 , 0.09901673])

In [19]:
state_key = repr(list(marketEnv.state_space[test_state_index]))

epsilon, value_cur_policy, sna_policy_dict_iter = sim_anneal_optimize(marketEnv, sna_policy_dict, k_max = 21)

In [20]:
epsilon

array([0.55836124, 0.36323051, 0.38531987, 0.33790228, 0.47502096,
       0.55385285, 0.69641612, 0.53383397, 0.57032858, 0.68976325])

In [21]:
value_cur_policy

array([0.10028156, 0.09676242, 0.10026411, 0.10267462, 0.09781705,
       0.09680415, 0.10061201, 0.09503043, 0.09803056, 0.10026991])

In [22]:
sna_policy_dict_iter[state_key][1].range_dic

{(0, 10): 0.18497496202549316,
 (10, 20): 0.11983932096451322,
 (20, 30): 0.17433225267461028,
 (30, 40): 0.047371245175546056,
 (40, 50): 0.19215071400096218,
 (50, 60): 0.021675673039184815,
 (60, 70): 0.08960173164100348,
 (70, 80): 0.09370135445562199,
 (80, 90): 0.0,
 (90, 100): 0.07635274602306476}