In [1]:
from opt.value_estimator import *
from environment.MarketEnv import *
from common.RangeMap import *
import numpy as np
from opt.bbo_sim_anneal import *

STATE_DIM = 2
ACTION_DIM = 11
BATCH_SIZE = 200

marketEnv = MarketEnv(action_size = ACTION_DIM, max_price = 100, max_inventory = 5, n_agents = 3)



In [2]:
marketEnv.action_space

array([ 0.        ,  9.09090909, 18.18181818, 27.27272727, 36.36363636,
       45.45454545, 54.54545455, 63.63636364, 72.72727273, 81.81818182,
       90.90909091])

In [3]:
range_dict = {
    (0, 10): 0.10,
    (10, 20): 0.10,
    (20, 30): 0.10,
    (30, 40): 0.10,
    (40, 50): 0.10,
    (50, 60): 0.10,
    (60, 70): 0.10,
    (70, 80): 0.10,
    (80, 90): 0.10,
    (90, 100): 0.10,
}

policy_dic = RangeMapDict(range_dict)

In [4]:
from opt.bbo_sim_anneal import *

alt_dic = perturb_policy(policy_dic.range_dic)
alt_dic

{(0, 10): 0.1,
 (10, 20): 0.1,
 (20, 30): 0.1,
 (30, 40): 0.1,
 (40, 50): 0.1,
 (50, 60): 0.1,
 (60, 70): 0.1,
 (70, 80): 0.1,
 (80, 90): 0.1,
 (90, 100): 0.1}

In [5]:
np.sum(list(alt_dic.values()))

1.0

In [6]:
all(v > 0.0 for v in policy_dic.range_dic.values())

True

In [7]:
np.sum(list(policy_dic.range_dic.values()))

1.0

In [9]:
# s -> n -> a
na_policy_dict = dict()
for n in range(marketEnv.n_agents):
    na_policy_dict[n] = policy_dic

# everyone same policy
sna_policy_dict = dict()
for s in range(marketEnv.state_space_size):
    key = repr(list(marketEnv.state_space[s]))
    sna_policy_dict[key] = na_policy_dict

In [10]:
repr(marketEnv.state_space[0])

'array([0., 0., 0., 0.])'

In [11]:
sna_policy_dict[repr([0.0, 0.0, 0.0, 0.0])][1][34]

0.1

In [12]:
marketEnv.action_space

array([ 0.        ,  9.09090909, 18.18181818, 27.27272727, 36.36363636,
       45.45454545, 54.54545455, 63.63636364, 72.72727273, 81.81818182,
       90.90909091])

In [13]:
value_vector, joint_action_vector = value_search_sample_policy_approx(marketEnv, sna_policy_dict, max_iter = 199)

In [14]:
test_state_index = 4
print(joint_action_vector[test_state_index])
print(marketEnv.state_space[test_state_index])
print(value_vector[test_state_index])

[45.45454545 54.54545455 54.54545455]
[0. 4. 0. 0.]
0.10307600010765472


In [15]:
check_state = marketEnv.state_space[test_state_index]
sna_policy_dict[repr(list(check_state))][0][21]

0.1

In [16]:
value_vector

array([0.10250701, 0.1026182 , 0.09818527, ..., 0.10179266, 0.09974585,
       0.10158037])

In [17]:
epsilon, value_cur_policy = sim_anneal_optimize(marketEnv, sna_policy_dict)

In [2]:
epsilon

NameError: name 'epsilon' is not defined