In [1]:
from opt.value_estimator import *
from environment.MarketEnv import *
from common.RangeMap import *
import numpy as np
from opt.bbo_sim_anneal import *


STATE_DIM = 2
ACTION_DIM = 4
BATCH_SIZE = 200

marketEnv = MarketEnv(action_size = ACTION_DIM, max_price = 100, max_inventory = 2, n_agents = 3)

range_dict = {
    (0, 10): 0.10,
    (10, 20): 0.10,
    (20, 30): 0.10,
    (30, 40): 0.10,
    (40, 50): 0.10,
    (50, 60): 0.10,
    (60, 70): 0.10,
    (70, 80): 0.10,
    (80, 90): 0.10,
    (90, 100): 0.10,
}

policy_dic = RangeMapDict(range_dict)

# s -> n -> a
na_policy_dict = dict()
for n in range(marketEnv.n_agents):
    na_policy_dict[n] = policy_dic

# everyone same policy
sna_policy_dict = dict()
for s in range(marketEnv.state_space_size):
    key = repr(list(marketEnv.state_space[s]))
    sna_policy_dict[key] = na_policy_dict

In [2]:
marketEnv.action_space

array([ 0., 25., 50., 75.])

In [3]:
value_vector, joint_action_vector = value_search_sample_policy_approx(marketEnv, sna_policy_dict, max_iter = 199)

In [4]:
test_state_index = 4
print(joint_action_vector[test_state_index])
print(marketEnv.state_space[test_state_index])
print(value_vector[test_state_index])

[50. 50. 50.]
[0. 0. 1. 0.]
0.10393366271819425


In [5]:
check_state = marketEnv.state_space[test_state_index]
sna_policy_dict[repr(list(check_state))][0][21]

0.1

In [6]:
value_vector

array([0.10283005, 0.09819384, 0.09745649, 0.10104839, 0.10393366,
       0.10281414, 0.10048995, 0.10004202, 0.10294739, 0.10102188,
       0.10075792, 0.10044854, 0.10444912, 0.10179398, 0.10128287,
       0.10216546, 0.10036944, 0.0983699 , 0.1021822 , 0.10129827,
       0.10267142, 0.10275927, 0.1008089 , 0.09885483, 0.10305004,
       0.10075015, 0.10130068, 0.10015049, 0.10202255, 0.10335185,
       0.1011269 , 0.10237477])

In [7]:
state_key = repr(list(marketEnv.state_space[test_state_index]))

epsilon, value_cur_policy = sim_anneal_optimize(marketEnv, sna_policy_dict)

In [8]:
sna_policy_dict[state_key][1].range_dic

{(0, 10): 0.1,
 (10, 20): 0.1,
 (20, 30): 0.1,
 (30, 40): 0.1,
 (40, 50): 0.1,
 (50, 60): 0.1,
 (60, 70): 0.1,
 (70, 80): 0.1,
 (80, 90): 0.1,
 (90, 100): 0.1}

In [10]:
epsilon

array([0.17275808, 0.16239458, 0.15820139, 0.15460117, 0.14675146,
       0.15550911, 0.16704244, 0.15639966, 0.15501168, 0.16551202,
       0.15362868, 0.14984565, 0.15278566, 0.16792837, 0.14643232,
       0.17371683, 0.12686941, 0.14939596, 0.15710854, 0.16522195,
       0.15469406, 0.16087735, 0.15024456, 0.13926345, 0.16029849,
       0.15865946, 0.16280007, 0.17393234, 0.13252643, 0.14853824,
       0.16540366, 0.15749721])

In [11]:
value_cur_policy

array([0.09606762, 0.10011156, 0.09825664, 0.10164757, 0.10056532,
       0.1050419 , 0.10120446, 0.10299962, 0.09821973, 0.09939792,
       0.10106925, 0.09698442, 0.10048358, 0.09611009, 0.10147068,
       0.10227849, 0.09875356, 0.10003877, 0.10103759, 0.09643417,
       0.10005487, 0.09933747, 0.10228385, 0.09784394, 0.09800244,
       0.1014091 , 0.10165551, 0.10221709, 0.0969811 , 0.09952829,
       0.10050191, 0.09661014])