In [158]:
import numpy as np

In [159]:
r = np.array( [[[3, 0], [6, 0]], [[2,0], [1, 0]]])
t = np.array( [[[[1,0], [0, 1]], [[1/3, 2/3], [0, 1]]], [[[1, 0], [0, 1]], [[1, 0], [0, 1]]]])
# r a1, a2, s
# r[:,:, 0]
# t a1, a2, s, s_next
# t[0, 1, 0]

p0 =[[0, 1], [1, 0]]
p1_0 =[[1, 0], [1, 0]]
p1_1 =[[0, 1], [1, 0]]


In [160]:
disc_fac = 3/4


p_0_1_0 = np.array([[1/3, 2/3],[0, 1]])
p_0_1_1 = np.array([[1, 0],[0, 1]])

In [161]:
Pinv_0_1_0 =np.linalg.inv(np.identity(2) - disc_fac * p_0_1_0)
Pinv_0_1_0

array([[1.33333333, 2.66666667],
       [0.        , 4.        ]])

In [162]:
r_0_1_0 =  np.array([6, 0])
r_0_1_0

array([6, 0])

In [163]:
np.matmul(Pinv_0_1_0, r_0_1_0)

array([8., 0.])

In [164]:
r_0_1_1 = np.array([1, 0])
Pinv_0_1_1 =np.linalg.inv(np.identity(2) - disc_fac * p_0_1_1)
Pinv_0_1_1

array([[4., 0.],
       [0., 4.]])

In [165]:
np.matmul(Pinv_0_1_1, r_0_1_1)

array([4., 0.])