In [107]:
import numpy as np

In [108]:
r = np.array( [[[3, 0], [6, 0]], [[2,0], [1, 0]]])

t = np.array( [[[[1,0], [0, 1]], [[1/3, 2/3], [0, 1]]], [[[1, 0], [0, 1]], [[1, 0], [0, 1]]]])

In [109]:
# r a1, a2, s
r[:,:, 0]

array([[3, 6],
       [2, 1]])

In [110]:
# t a1, a2, s, s_next
t[0, 1, 0]

array([0.33333333, 0.66666667])

In [111]:
p0 =[[0, 1], [1, 0]]

p1_0 =[[1, 0], [1, 0]]
p1_1 =[[0, 1], [1, 0]]


In [112]:
p_0_1_0 = np.array([[1/3, 2/3],[0, 1]])
p_0_1_1 = np.array([[1, 0],[0, 1]])

In [113]:
disc_fac = 3/4
Pinv_0_1_0 =np.linalg.inv(np.identity(2) - disc_fac * p_0_1_0)
Pinv_0_1_0

array([[1.33333333, 2.66666667],
       [0.        , 4.        ]])

In [114]:
r_0_1_0 =  np.array([6, 0])
r_0_1_0

array([6, 0])

In [115]:
np.matmul(Pinv_0_1_0, r_0_1_0)

array([8., 0.])

In [116]:
r_0_1_1 =  np.array([1, 0])