In [1]:
from opt.value_estimator import *
from environment.MarketEnv import *
from common.RangeMap import *
import numpy as np
from opt.bbo_sim_anneal import *

STATE_DIM = 2
ACTION_DIM = 10
BATCH_SIZE = 200

marketEnv = MarketEnv(action_size = ACTION_DIM, max_price = 100, max_inventory = 1, n_agents = 3)

range_dict = {
    (0, 10): 0.10,
    (10, 20): 0.10,
    (20, 30): 0.10,
    (30, 40): 0.10,
    (40, 50): 0.10,
    (50, 60): 0.10,
    (60, 70): 0.10,
    (70, 80): 0.10,
    (80, 90): 0.10,
    (90, 100): 0.10,
}

policy_dic = RangeMapDict(range_dict)

# s -> n -> a
na_policy_dict = dict()
for n in range(marketEnv.n_agents):
    na_policy_dict[n] = policy_dic

# everyone same policy
sna_policy_dict = dict()
for s in range(marketEnv.state_space_size):
    key = repr(list(marketEnv.state_space[s]))
    sna_policy_dict[key] = na_policy_dict

In [2]:
marketEnv.action_space

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [3]:
marketEnv.state_space

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.],
       [ 0.,  0.,  0., 10.],
       [ 0.,  1.,  0., 10.],
       [ 1.,  0.,  0., 10.],
       [ 1.,  1.,  0., 10.],
       [ 0.,  0.,  1., 10.],
       [ 0.,  1.,  1., 10.],
       [ 1.,  0.,  1., 10.],
       [ 1.,  1.,  1., 10.],
       [ 0.,  0.,  0., 20.],
       [ 0.,  1.,  0., 20.],
       [ 1.,  0.,  0., 20.],
       [ 1.,  1.,  0., 20.],
       [ 0.,  0.,  1., 20.],
       [ 0.,  1.,  1., 20.],
       [ 1.,  0.,  1., 20.],
       [ 1.,  1.,  1., 20.],
       [ 0.,  0.,  0., 30.],
       [ 0.,  1.,  0., 30.],
       [ 1.,  0.,  0., 30.],
       [ 1.,  1.,  0., 30.],
       [ 0.,  0.,  1., 30.],
       [ 0.,  1.,  1., 30.],
       [ 1.,  0.,  1., 30.],
       [ 1.,  1.,  1., 30.],
       [ 0.,  0.,  0., 40.],
       [ 0.,  1.,  0., 40.],
       [ 1.,  

In [4]:
value_vector, joint_action_vector = value_search_sample_policy_approx(marketEnv, sna_policy_dict, max_iter = 199)

In [5]:
test_state_index = 1
print(joint_action_vector[test_state_index])
print(marketEnv.state_space[test_state_index])
print(value_vector[test_state_index])

[50. 50. 50.]
[0. 1. 0. 0.]
0.10215222537966337


In [6]:
check_state = marketEnv.state_space[test_state_index]
sna_policy_dict[repr(list(check_state))][0][21]

0.1

In [7]:
value_vector

array([0.10041636, 0.10215223, 0.09816376, 0.10201404, 0.09965963,
       0.10008018, 0.09987869, 0.10126282, 0.09890804, 0.1002562 ,
       0.10111638, 0.10036793, 0.1003184 , 0.10286034, 0.0978781 ,
       0.10180735, 0.09983924, 0.10094402, 0.10132897, 0.09776462,
       0.10046289, 0.10218522, 0.09683561, 0.10028284, 0.10044557,
       0.10031116, 0.09999722, 0.10029896, 0.10082497, 0.10026557,
       0.09911723, 0.0996602 , 0.09972802, 0.10469701, 0.10207807,
       0.10145879, 0.09966467, 0.09932048, 0.10117614, 0.10375041,
       0.10025911, 0.10050662, 0.09905663, 0.1014252 , 0.10158077,
       0.09962791, 0.10247456, 0.1007265 , 0.10203197, 0.10229415,
       0.10181821, 0.09829284, 0.10066718, 0.09978554, 0.0995604 ,
       0.10168271, 0.09882018, 0.10208091, 0.09950525, 0.10148417,
       0.09728819, 0.09898993, 0.10082869, 0.09728013, 0.09742047,
       0.10026283, 0.10075608, 0.10172722, 0.09943421, 0.10017048,
       0.09864747, 0.0995759 , 0.09932775, 0.09932215, 0.10634

In [8]:
state_key = repr(list(marketEnv.state_space[test_state_index]))

epsilon, value_cur_policy, sna_policy_dict_iter = sim_anneal_optimize(marketEnv, sna_policy_dict, k_max = 21)

In [9]:
epsilon

array([0.21834592, 0.25062033, 0.04732499, 0.04166262, 0.16559775,
       0.15376133, 0.07504495, 0.22558251, 0.02267558, 0.11468588,
       0.13061144, 0.35935639, 0.19590595, 0.08815372, 0.32357567,
       0.07233314, 0.01707323, 0.05148564, 0.0583591 , 0.1681806 ,
       0.18909606, 0.14139747, 0.05852367, 0.16427823, 0.04716254,
       0.43093203, 0.05577088, 0.08325803, 0.18574181, 0.08885716,
       0.15505188, 0.41113608, 0.11428815, 0.02725958, 0.11184167,
       0.06351799, 0.20019822, 0.07217576, 0.05472021, 0.17866053,
       0.02370847, 0.60049914, 0.06592273, 0.14547693, 0.12723366,
       0.05853023, 0.16041842, 0.28201194, 0.112952  , 0.10143597,
       0.05189525, 0.49789096, 0.31201804, 0.15991644, 0.21828878,
       0.12215237, 0.06486413, 0.10270924, 0.19498941, 0.11052291,
       0.1714823 , 0.13587606, 0.04802202, 0.17007765, 0.10080757,
       0.06183843, 0.09821891, 0.4044995 , 0.17938468, 0.162896  ,
       0.19979182, 0.33331825, 0.42238206, 0.269544  , 0.45663

In [10]:
value_cur_policy

array([0.09993732, 0.10228954, 0.09692871, 0.10009551, 0.10038631,
       0.09878274, 0.10198124, 0.09813297, 0.10091057, 0.10104523,
       0.10361212, 0.10206846, 0.09993274, 0.10058675, 0.09997449,
       0.10031713, 0.10203648, 0.09979246, 0.10007736, 0.09985627,
       0.10002459, 0.09878021, 0.10064605, 0.09803221, 0.10285588,
       0.0977042 , 0.09857874, 0.09887724, 0.09467271, 0.10158357,
       0.09945515, 0.10174249, 0.09969027, 0.10016519, 0.10200337,
       0.09930613, 0.09908957, 0.10101051, 0.10239795, 0.1016512 ,
       0.09972048, 0.1046084 , 0.09880283, 0.10165823, 0.09723127,
       0.09894704, 0.10019407, 0.09899349, 0.1005191 , 0.09765052,
       0.10428077, 0.09862533, 0.10042657, 0.09849462, 0.0990036 ,
       0.09802343, 0.0988379 , 0.09841644, 0.09990274, 0.09876332,
       0.09817754, 0.10059977, 0.09904531, 0.10044075, 0.0990674 ,
       0.10149289, 0.09724052, 0.10228447, 0.09777307, 0.09796206,
       0.1016765 , 0.10052132, 0.0994978 , 0.10237004, 0.09783

In [11]:
sna_policy_dict_iter[state_key][1].range_dic

{(0, 10): 0.07445391203175868,
 (10, 20): 0.09214297077051702,
 (20, 30): 0.07490324028223702,
 (30, 40): 0.09843316204066244,
 (40, 50): 0.08204893028803584,
 (50, 60): 0.11854889248626138,
 (60, 70): 0.07940840874659082,
 (70, 80): 0.10579012889494596,
 (80, 90): 0.15109180016445542,
 (90, 100): 0.12317855429453532}